const catalog =
[

    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E1.jpeg",
        'Quantity': 'Quantity: 2',
        'Status1': 'E1 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E2.jpeg",
        'Quantity': 'Quantity: 2',
        'Status1': 'E2 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E3.jpeg",
        'Quantity': 'Quantity: 1',
        'Status1': 'E3 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E4.jpeg",
        'Quantity': 'Quantity: 1',
        'Status1': 'E4 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E5.jpeg",
        'Quantity': 'Quantity: 1',
        'Status1': 'E5 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E6.jpeg",
        'Quantity': 'Quantity: 1',
        'Status1': 'E6 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E7.jpeg",
        'Quantity': 'Quantity: 1',
        'Status1': 'E7 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E8.jpeg",
        'Quantity': 'Quantity: 1',
        'Status1': 'E8 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E9.jpeg",
        'Quantity': 'Quantity: 2',
        'Status1': 'E9 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E10.jpeg",
        'Quantity': 'Quantity: 1',
        'Status1': 'E10 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E11.jpeg",
        'Quantity': 'Quantity: 1',
        'Status1': 'E11 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E12.jpeg",
        'Quantity': 'Quantity: 1',
        'Status1': 'E12 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E13.jpeg",
        'Quantity': 'Quantity: 1',
        'Status1': 'E13 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E14.jpeg",
        'Quantity': 'Quantity: 2',
        'Status1': 'E14 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E15.jpeg",
        'Quantity': 'Quantity: 1',
        'Status1': 'E15 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E16.jpeg",
        'Quantity': 'Quantity: 1',
        'Status1': 'E16 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E17.jpeg",
        'Quantity': 'Quantity: 2',
        'Status1': 'E17 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E18.jpeg",
        'Quantity': 'Quantity: 2',
        'Status1': 'E18 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E19.jpeg",
        'Quantity': 'Quantity: 1',
        'Status1': 'E19 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E20.jpeg",
        'Quantity': 'Quantity: 1',
        'Status1': 'E20 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E21.jpeg",
        'Quantity': 'Quantity: 1',
        'Status1': 'E21 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E22.jpeg",
        'Quantity': 'Quantity: 2',
        'Status1': 'E22 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E23.jpeg",
        'Quantity': 'Quantity: 2',
        'Status1': 'E23 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E24.jpeg",
        'Quantity': 'Quantity: 2',
        'Status1': 'E24 - Available',
    },
    {
        'Type': 'Shawl',
        'Material': 'Chiffon',
        'Image': "../catalog/Shawl/E25.jpeg",
        'Quantity': 'Quantity: 2',
        'Status1': 'E25 - Available',
    },


]
/*
{
    'Type': 'Shawl',
    'Material': 'Cotton Eyelash',
    'Image': "../catalog/Shawl/C1-C5.jpeg",
    'Status1': 'C1 - Available',
    'Status2': 'C2 - Sold Out',
    'Status3': 'C3 - Sold Out',
    'Status4': 'C4 - Available',
    'Status5': 'C5 - Available',
    'Link': "../catalog/Shawl/C1-C5.jpeg"
},
{
    'Type': 'Shawl',
    'Material': 'Cotton Eyelash',
    'Image': "../catalog/Shawl/C6-C10.jpeg",
    'Status1': 'C6 - Sold Out',
    'Status2': 'C7 - Available',
    'Status3': 'C8 - Available',
    'Status4': 'C9 - Available',
    'Status5': 'C10 - Available'
},
{
    'Type': 'Shawl',
    'Material': 'Cotton Eyelash',
    'Image': "../catalog/Shawl/C11-C15.jpeg",
    'Status1': 'C11 - Available',
    'Status2': 'C12 - Available',
    'Status3': 'C13 - Available',
    'Status4': 'C14 - Available',
    'Status5': 'C15 - Available'
},
{
    'Type': 'Shawl',
    'Material': 'Cotton Eyelash',
    'Image': "../catalog/Shawl/C16-C20.jpeg",
    'Status1': 'C16 - Available',
    'Status2': 'C17 - Available',
    'Status3': 'C18 - Available',
    'Status4': 'C19 - Available',
    'Status5': 'C20 - Available'
},
{
    'Type': 'Shawl',
    'Material': 'Satin',
    'Image': "../catalog/Shawl/S1-S5.jpeg",
    'Status1': 'S1 - Available',
    'Status2': 'S2 - Available',
    'Status3': 'S3 - Available',
    'Status4': 'S4 - Available',
    'Status5': 'S5 - Available'
},
{
    'Type': 'Shawl',
    'Material': 'Satin',
    'Image': "../catalog/Shawl/S6-S10.jpeg",
    'Status1': 'S6 - Available',
    'Status2': 'S7 - Available',
    'Status3': 'S8 - Available',
    'Status4': 'S9 - Available',
    'Status5': 'S10 - Available'
},
{
    'Type': 'Shawl',
    'Material': 'Satin',
    'Image': "../catalog/Shawl/S11-S15.jpeg",
    'Status1': 'S11 - Available',
    'Status2': 'S12 - Available',
    'Status3': 'S13 - Available',
    'Status4': 'S14 - Available',
    'Status5': 'S15 - Available'
},
{
    'Type': 'Shawl',
    'Material': 'Satin',
    'Image': "../catalog/Shawl/S16-S20.jpeg",
    'Status1': 'S16 - Available',
    'Status2': 'S17 - Available',
    'Status3': 'S18 - Available',
    'Status4': 'S19 - Available',
    'Status5': 'S20 - Available'
},
{
    'Type': 'Shawl',
    'Material': 'Chiffon Eyelash',
    'Image': "../catalog/Shawl/Ch1-Ch4.jpeg",
    'Status1': 'Ch1 - Available', 
    'Status2': 'Ch2 - Available',
    'Status3': 'Ch3 - Available',
    'Status4': 'Ch4 - Available',
    'Status5': ''
},
{
    'Type': 'Shawl',
    'Material': 'Chiffon Eyelash',
    'Image': "../catalog/Shawl/Ch5-Ch8.jpeg",
    'Status1': 'Ch5 - Available', 
    'Status2': 'Ch6 - Available',
    'Status3': 'Ch7 - Available',
    'Status4': 'Ch8 - Available',
    'Status5': ''
},
{
    'Type': 'Shawl',
    'Material': 'Chiffon Eyelash',
    'Image': "../catalog/Shawl/Ch9-Ch12.jpeg",
    'Status1': 'Ch9 - Available', 
    'Status2': 'Ch10 - Available',
    'Status3': 'Ch11 - Available',
    'Status4': 'Ch12 - Available',
    'Status5': ''
},
{
    'Type': 'Shawl',
    'Material': 'Chiffon Eyelash',
    'Image': "../catalog/Shawl/Ch13-Ch16.jpeg",
    'Status1': 'Ch13 - Available', 
    'Status2': 'Ch14 - Available',
    'Status3': 'Ch15 - Available',
    'Status4': 'Ch16 - Available',
    'Status5': ''
},
{
    'Type': 'Bawal',
    'Material': 'Cotton',
    'Image': "../catalog/Bawal/B1-B10.jpg",
    'Status1': 'B1 - Sold Out B2 - Sold Out', 
    'Status2': 'B3 - Available B4 - Available',
    'Status3': 'B5 - Available B6 - Available',
    'Status4': 'B7 - Available B8 - Available',
    'Status5': 'B9 - Available B10 - Available'
},
{
    'Type': 'Bawal',
    'Material': 'Cotton',
    'Image': "../catalog/Bawal/B11-B20.jpeg",
    'Status1': 'B11 - Available B12 - Available', 
    'Status2': 'B13 - Available B14 - Available',
    'Status3': 'B15 - Available B16 - Available',
    'Status4': 'B17 - Available B18 - Available',
    'Status5': 'B19 - Available B20 - Available'
},
{
    'Type': 'Bawal',
    'Material': 'Cotton',
    'Image': "../catalog/Bawal/BC1-BC10.jpg",
    'Status1': 'BC1 -Available BC2 -Available', 
    'Status2': 'BC3 -Available BC4 -Available',
    'Status3': 'BC5 -Available BC6 -Available',
    'Status4': 'BC7 -Available BC8 -Available',
    'Status5': 'BC9 -Available BC10 -Available'
},    
{
    'Type': 'Bawal',
    'Material': 'Cotton',
    'Image': "../catalog/Bawal/BC11-BC20.jpeg",
    'Status1': 'BC11 - Available BC12 - Sold Out', 
    'Status2': 'BC13 - Available BC14 - Available',
    'Status3': 'BC15 - Available BC16 - Available',
    'Status4': 'BC17 - Available BC18 - Available',
    'Status5': 'BC19 - Available BC20 - Available'
},
*/
